import joblib
import pickle
import json
import xgboost as xgb
import numpy as np
from pathlib import Path

# Paths based on the codebase config
MODELS_DIR = Path("Machine_Learning_Course/Data/PianoMotion10M/models")
MODELS_DIR_LOCAL = Path("models")

def migrate_local_models():
    """Migrate the main local rf_model.pkl generated by train_gpu.py if it exists."""
    pkl_model_path = MODELS_DIR_LOCAL / "rf_model.pkl"
    json_model_path = MODELS_DIR_LOCAL / "rf_model.json"

    if pkl_model_path.exists():
        print(f"Migrating {pkl_model_path} to JSON...")
        try:
            # We don't know exactly if it's joblib or pickle, but usually joblib works for both
            model = joblib.load(pkl_model_path)
            model.save_model(json_model_path)
            print(f"Successfully migrated to {json_model_path}")
        except Exception as e:
            print(f"Error migrating {pkl_model_path}: {e}")
    else:
        print(f"{pkl_model_path} not found. Skipping local model migration.")

def migrate_runtime_artifacts():
    """Migrate the artifacts used by main_runtime.py (model, scaler, features)."""
    if not MODELS_DIR.exists():
        print(f"Runtime models directory {MODELS_DIR} not found. Skipping.")
        return

    m_pkl = MODELS_DIR / "rf_model.pkl"
    s_pkl = MODELS_DIR / "scaler.pkl"
    f_pkl = MODELS_DIR / "selected_features.pkl"

    m_json = MODELS_DIR / "rf_model.json"
    s_json = MODELS_DIR / "scaler.json"
    f_json = MODELS_DIR / "selected_features.json"

    # Migrate Model
    if m_pkl.exists():
        print(f"Migrating {m_pkl} to JSON...")
        try:
            model = joblib.load(m_pkl)
            model.save_model(m_json)
            print(f"Successfully migrated to {m_json}")
        except Exception as e:
            print(f"Error migrating {m_pkl}: {e}")

    # Migrate Scaler
    if s_pkl.exists():
        print(f"Migrating {s_pkl} to JSON...")
        try:
            scaler = joblib.load(s_pkl)
            # Standard Scaler expects mean_ and scale_ to exist
            scaler_data = {
                'mean': scaler.mean_.tolist() if hasattr(scaler, 'mean_') else [],
                'scale': scaler.scale_.tolist() if hasattr(scaler, 'scale_') else []
            }
            with open(s_json, 'w') as f:
                json.dump(scaler_data, f)
            print(f"Successfully migrated to {s_json}")
        except Exception as e:
            print(f"Error migrating {s_pkl}: {e}")

    # Migrate Features
    if f_pkl.exists():
        print(f"Migrating {f_pkl} to JSON...")
        try:
            features = joblib.load(f_pkl)
            # Usually features is a list of strings
            with open(f_json, 'w') as f:
                json.dump(features, f)
            print(f"Successfully migrated to {f_json}")
        except Exception as e:
            print(f"Error migrating {f_pkl}: {e}")

if __name__ == "__main__":
    migrate_local_models()
    migrate_runtime_artifacts()
    print("Migration complete.")
